name: Python Tests

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    Actions:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ["3.11"]
        services:
            postgres:
                image: postgres
                env:
                    POSTGRES_USER: fastapi
                    POSTGRES_PASSWORD: fastapi
                    POSTGRES_DB: fastapi_test
                options: >-
                    --health-cmd pg_isready
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5

        steps:
            - uses: actions/checkout@v3
            - name: Set up python ${{ matrix.python-version }}
              uses: actions/setup-python@v4
              with:
                python-version: ${{ matrix.python-version }}
            - name: Install Dependencies
              run: |
                python -m pip install --upgrade pip
                pip install pytest
                if [-f requirements.txt]; then pip install -r requirements.txt; fi
              env:
                TEST_DATABASE_URL: postgresql+asyncpg://fastapi:fastapi@postgres:5432/fastapi_test
            - name: Test with pytest
              run: |
                pytest
